language: csharp
solution: GoogleSearch.sln
install:
  - nuget restore GoogleSearch.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release GoogleSearch.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./GoogleSearch.Tests/bin/Release/GoogleSearch.Tests.dll